<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>BitMiracle.Jpeg</RootNamespace>
    <OutputPath>..\Result\</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

    <ItemGroup>
    <Compile Include="..\cdJpeg\ADDON_MESSAGE_CODE.cs">
      <Link>ADDON_MESSAGE_CODE.cs</Link>
    </Compile>
    <Compile Include="..\cdJpeg\cdjpeg_progress_mgr.cs">
      <Link>cdjpeg_progress_mgr.cs</Link>
    </Compile>
    <Compile Include="..\cdJpeg\cdjpeg_utils.cs">
      <Link>cdjpeg_utils.cs</Link>
    </Compile>
    <Compile Include="..\cdJpeg\cd_jpeg_error_mgr.cs">
      <Link>cd_jpeg_error_mgr.cs</Link>
    </Compile>
    <Compile Include="..\AssemblyVersion.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibJpeg\LibJpeg.csproj">
      <Name>LibJpeg</Name>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <None Include="app.config" />
  </ItemGroup>

  <PropertyGroup>
    <PreBuildEvent Condition="'$(TargetFramework)'=='net90' And '$(OS)'=='Windows'">cd "$(SolutionDir)"
update_version_info.bat "$(ProjectDir)AssemblyVersion.cs"</PreBuildEvent>
  </PropertyGroup>
</Project>
